### ISSUE TITLE
Make app.authenticate({ type: 'local', email, password }) more secure

### ISSUE THREAD

**Issue by eddyystop** [feathersjs/feathers-authentication-management#10]
```javascript
// Authenticate user and log on if user is verified.
var cbCalled = false;
app.authenticate({ type: 'local', email, password })
  .then((result) => {
    const user = result.data;
    if (!user || !user.isVerified) {
      app.logout();
      cb(new Error(user ? 'User\'s email is not verified.' : 'No user returned.'));
      return;
    }
    cbCalled = true;
    cb(null, user);
  })
  .catch((err) => {
    if (!cbCalled) { cb(err); } // ignore throws from .then( cb(null, user) )
  });
````

Since this is javascript running at the front end, a unverified user can always manually log himself in via browser's console (simply run app.authenticate({ type: 'local', email, password }) as long as he could find how to access the app), bypassing the !user.verified check. I wonder if there is any decent way to avoid this.

I was thinking authenticate, if configured to do so, would check user.isVerified if it existed.

**Comment by daffl** [comment]
Wouldn't subsequent requests still fail though?

**Comment by beeplin** [comment]
yes I think @daffl is right. As long as we have correct before hooks, no need to worry about this.
