### ISSUE TITLE
Errors returned are vague

### ISSUE THREAD

**Issue by codingfriend1** [feathersjs/feathers-authentication-management#12]
### Steps to reproduce

(First please check that this issue is not already solved as [described
here](https://github.com/feathersjs/feathers/blob/master/.github/contributing.md#report-a-bug))

- [ ] Tell us what broke. The more detailed the better.
- [ ] If you can, please create a simple example that reproduces the issue and link to a gist, jsbin, repo, etc.

Trying to send a reset password error when your account has not been verified.

### Expected behavior
Client should say "User is not verified."

### Actual behavior
Server logs say BadRequest: User is not verified.
However client side says "Request failed with status code 400."

### System configuration
Feathers Authentication Management 0.1.6

**Module versions** (especially the part that's not working):
**NodeJS version**:
v7.4.0
**Operating System**:
Mac
**Browser Version**:
Chrome
**React Native Version**:

**Module Loader**:
Webpack

**Comment by codingfriend1** [comment]
Sorry, this was an issue with axios library and not feathers authentication management. In postman is returns the correct error.

**Comment by WebbizAdmin** [comment]
How do you resolve the AXIOS issue. Im facing the same issue.
