### ISSUE TITLE
Question regarding 'resetPassword'

### ISSUE THREAD

**Issue by MHerszak** [feathersjs/feathers-authentication-management#15]
I had some issues with `patchUser`:

```
function patchUser (user, patchToUser) {
    return users.patch(user[usersIdName], patchToUser, {}) // needs users from closure
      .then(() => Object.assign(user, patchToUser));
  }
```
I saw that none of my fields was actually changed. I thought patch would come with its own $set but it seems that password is not actually changed after a reset. All I did is, I added the $set and it worked:
```
function patchUser (user, patchToUser) {
    return users.patch(user[usersIdName], { $set: patchToUser }, {}) // needs users from closure
      .then(() => Object.assign(user, patchToUser));
  }
```
Do you know what is happening here?

**Comment by eddyystop** [comment]
You don't mention which database you are using. The DB model defn, if one
is required, is needed also.

You should check for compatibility issues between the model and the
before/after values being patched.

If the model is compatible, then this would seem to be more an issue with
the database adapter than with this repo. Perhaps it'll be more productive
to create an issue for that adapter.

**Comment by MHerszak** [comment]
Upps, sorry. I am using feathers-mongoose.

**Comment by eddyystop** [comment]
You still have not addressed the rest of my comments.

**Comment by MHerszak** [comment]
I am using "feathers-mongoose": "^3.6.2",

```
export const userSchema = new Schema({
  email: { type: String, index: { unique: true } },
  password: { type: String },
  resetExpires: { type: Date },
  resetToken: { type: String },
  resetShortToken: { type: String },
  isVerified: { type: Boolean },
});
```

What do you mean by compatibility issue between the model and the before and after values?

**Comment by eddyystop** [comment]
Perhaps the repo tries to write values which are incompatible with a
field's model defn.
