### ISSUE TITLE
Missing doc?

### ISSUE THREAD

**Issue by tention** [feathersjs/feathers-authentication-management#18]
Couldn't access the doc anymore. Is there a new link for it?

https://docs.feathersjs.com/v/auk/authentication/management.html

**Comment by eddyystop** [comment]
We're aware of this issue and will fix it soon. It happened when we moving the Auk docs toward live.

You can still read it from the GitHub archieves:
https://github.com/feathersjs/feathers-docs/blob/c0aa2f8944f527390fe95196e0df92ed297a1c6f/authentication/management.md
