### ISSUE TITLE
getUserData never hits 'User not found'

### ISSUE THREAD

**Issue by cpsubrian** [feathersjs/feathers-authentication-management#25]
In `getUserData`, my app never hits the 'User not found' error. The reason is because, in my results, total is the string `"0"`, not the integer `0`.  See https://github.com/feathersjs/feathers-authentication-management/blob/master/src/helpers.js#L66

Is this something weird going on in my feather app or is this normal, and the code here should be updated to use an `==` or manually test both types?

Sample result for empty users query:

```
{ total: '0', limit: 10, skip: 0, data: [] }
```

**Comment by eddyystop** [comment]
`getUserData` is a helper function used by the functions exposed by the service. Which service action are you calling which results in `getUserData` being called?

If you are calling it directly, how are you doing so?

**Comment by cpsubrian** [comment]
I'm well aware its a helper function :smile:, I traced my problem to `helpers.js` after all. I'm triggering a 'resendVerifySignup' in my test suite. I traced this through to the user service query that results in the above data (`total === '0'`). I'm working on tracing through how the total gets to be a string in the first place, but I expect to find it somewhere in feathers core. 

```js
it('fails to resendVerifySignup on a non-existent user', () => {
  return Promise.resolve()
    .then(() => {
      return app.service(options.path).create({
        action: 'resendVerifySignup',
        value: {
          email: 'nonexistent@email.com'
        }
      })
    })
    .then(() => {
      throw new Error('There should be an error, not a result')
    })
    .catch((err) => {
      expect(err.code).toBe(400)
      expect(err.message).toBe('User not found.')
    })
})
```

**Comment by cpsubrian** [comment]
Not sure if I'm taking the docs too literally, but they also show total as a string: https://legacy.docs.feathersjs.com/databases/pagination.html

```js
{
  "total": "<total number of records>",
  "limit": "<max number of items per page>",
  "skip": "<number of skipped items (offset)>",
  "data": [/* data */]
}
```

**Comment by eddyystop** [comment]
Yes, I think that's a bit too literal. ;)

I've never heard of `hook.result.total` being a string. I don't refer to it much myself though.

It would be fortunate if you can reproduce this consistently. I also think this occurs outside this repo.

I await your conclusions with baited breath. ;)

**Comment by cpsubrian** [comment]
It turns out the database adapter returns strings in count queries, so I'd say the problem doesn't lie in this module. Will file an issue over there.
