### ISSUE TITLE
Does this package really need to require ECMAScript 2015?

### ISSUE THREAD

**Issue by shawnlauzon** [feathersjs/feathers-authentication-management#29]
This package uses the `...` operator liberally, which means that users need to use a newer version of Node or Babel. Since feathers itself works on older versions of node, I'm wondering if this was a conscious decision on the part of the developers to support only newer versions?

At least, a warning should probably be added to the docs. I haven't yet created a PR for this because I wanted to start a conversation first.

**Comment by daffl** [comment]
All our packages are being compiled and published using Babel and are compatible with Node 4+. If you want to use the cloned repository directly you will have to run `npm run compile` and then require files out of the `lib/` folder.

**Comment by shawnlauzon** [comment]
That's odd. You're right, as I look in the `node_modules` directory, there aren't any spread operators. But when I added it, my Node v4 server complained with `SyntaxError: Unexpected token ...` and the cloned repository didn't even exist on that node. Oh well, thanks for the response.

**Comment by eddyystop** [comment]
We push `src/` to GitHub, and published `lib/` on npm. Sometimes `src/` is used to understand what is going on while debugging on `lib/`.
