### ISSUE TITLE
Got "More than 1 user selected" message if a wrong verifyToken is provided

### ISSUE THREAD

**Issue by sonycamera** [feathersjs/feathers-authentication-management#39]
### Steps to reproduce

- [ ] If I send verifySignup request with a wrong verifyToken, I got "More than 1 user selected" error message

### Expected behavior
It should return "User not found" error message.

### Actual behavior
got "More than 1 user selected" error message.

### System configuration

feathers-authentication-management 0.1.6
feathers-knex 2.6.3
knex 0.12.9
pg 6.1.5

I looked into helper.js in feathers-authentication-management, the error seems to be in getUserData():
```
  if (Array.isArray(data) ? data.length === 0 : data.total === 0) {
    throw new errors.BadRequest('User not found.', { errors: { $className: 'badParams' } });
  }
  ...
```
And the data returned in verifySignup(`users.find({ query: query }).then(...)`) is:
`{"total":"0","limit":5,"skip":0,"data":[]}`

`total` is string, but the comparison (`data.total === 0`) expects integer. I'm not sure if it should be fixed in feathers-authentication-management or feathers-knex.

**Comment by eddyystop** [comment]
Its a problem with paginated/non-paginated services.

**Comment by eddyystop** [comment]
The problem was in the adapter which returned a string in certain circumstances.
