### ISSUE TITLE
Allow user to reset password if not yet verified

### ISSUE THREAD

**Issue by shawnlauzon** [feathersjs/feathers-authentication-management#41]
If a user has been created and a password set, but has not yet been verified, there seems to be no way to reset the password. 

Perhaps I'm missing something, but I don't see why a user needs to be verified to reset the password. Without this, an unverified user who has forgotten their password has no way to reset it.

1. Create user
2. Call "sendResetPwd"
3. Get error "User is not verified".

### Expected behavior
Token is sent to the user through email or SMS or whatever identifies the user.

### Actual behavior
Error "User is not verified".

**Comment by eddyystop** [comment]
"an unverified user who has forgotten their password has no way to reset it"

I don't see a problem with the existing, secure implementation. The user can confirm the verification email. He can request another be sent if the original verification email is lost. Once that is done, he can request a password reset email be sent, which allows him to change the password.

This process should only take only a few minutes as these emails should be received shortly after they are sent.

If you are suggesting we allow passwords for unverified users to be changed without providing the currect password (which the user has forgotten), that would be a security hole.

**Comment by shawnlauzon** [comment]
Yes, what you are suggesting does work, but the user experience of getting an email, clicking on the link getting another email, and clicking on that link (or in our case two separate SMS codes and entering the codes on the phone) are awkward.

Also, I don't understand how this provides additional security, because for both the verification and the password reset I'm sending the same exact information: just the phone number. Entering the phone number twice instead of once does not provide any additional security.

Very possibly I'm missing something basic. So, what security hole is being plugged by requiring the user to be verified before changing the password?

**Comment by eddyystop** [comment]
One theoretical attack vector starts with creating a large number of new users, each of which sends a verification short token to non-existant tel#s. Then sending the server random short tokens to find a valid one. (This of course leaves rather obvious evidence.)

Alternatively, random tokens could be tried periodically over a long period of time. This would be noticed only if the server logged verification attempts and analyzed for this.

I'm concerned that your suggestion may produce two tokens per new user, doubling the effectiveness of such attacks. I'm not sure this is worth getting a convenience method for an edge cage which already has a secure solution.

I would be more worried about this if a 5-digit token was being used rather than the default 6-digit one. Furthermore, this attack only get the attacker to a sign on page.

Thoughts?

**Comment by jerfowler** [comment]
I agree with @shawnlauzon. Isn't the fact that they received an email/text for a reset the same as receiving a verification email/text? So by using that token, they've both verified themselves and requested to reset their password. That should be a one-shot step. 

Use case: you're migrating a ton of users from one system to another and their account has been given a randomly generated password, which they don't know. They've received the verification email and they've deleted or it was lost in a spam quarantine. Months later they need access again and try to reset their passwords, but can't? So, you're saying they need to perform two steps? Verify then reset? That would be a horrible user experience.

I'm also not following your attack vector example. So, an attacker creates a ton of new users. (Which should be pretty noticeable rather immediately) Then they try to send the server a series of tokens to gain access to... a brand new account they just created themselves? All you have to do is review the logs, notice the users and disable the ones that were created by the same IP address and make they revalidate themselves by resting their password.

User experience trumps verification here. The security concern is rather weak considering it only takes a few minutes to create a free Gmail account or an anonymous Google voice text number. A hell-of-a-lot faster that brute forcing a random token. An attacker wouldn't even bother and verification doesn't prevent unsavory people getting access if you have an app open to the general public. 

To tighten it up a bit, you could always require a longer token when the account hasn't been verified to reduce the chances of a successful brute force attack.

With all that said, my registration form only has name & email and users won't be able to create a password **until** they've verified their email first.

**Comment by eddyystop** [comment]
You are both welcome to submit a PR for consideration.

**Comment by marbemac** [comment]
We ran into this as well - created a quick little PR. I don't see any security issues.

Having a user request a new verify user email and then a reset password email is no more secure than just requesting a reset password email.

**Comment by eddyystop** [comment]
Handled in https://github.com/feathersjs/feathers-authentication-management/pull/61

**Comment by ajimiathul** [comment]
Any example of implementation?
