### ISSUE TITLE
option to customize `sanitizeUserForClient` function

### ISSUE THREAD

**Issue by markacola** [feathersjs/feathers-authentication-management#46]
### Steps to reproduce
I have a use case where sensitive data is stored on the user object, which has sanitation hooks on the user service when the provider is remote.
These sanitation hooks are circumvented by the authManagement service (it being a server-side call) leading to the entire user object being returned, and subsequently sent down to the client. In these cases the client may be completely anonymous.

### Expected behavior
Should be able to customize the sanitation of the user returned from the authManagement service.

### Actual behavior
User contains all data, save what the authManagement service deems appropriate to remove.

### System configuration
N/A

I am happy to implement this an send a PR across, just let me know.

It might be beneficial to also allow customized functions for other helpers.

**Comment by eddyystop** [comment]
Being delt with in https://github.com/feathersjs/feathers-authentication-management/pull/47
