### ISSUE TITLE
populateUser hook in doc

### ISSUE THREAD

**Issue by sylvainlap** [feathersjs/feathers-authentication-management#52]
Hi,

In documentation (https://github.com/feathersjs/feathers-authentication-management/blob/master/docs.md), it is said that populateUser hook is required:

`hooks.iff(isAction('passwordChange', 'identityChange'), auth.populateUser()),`

However, this hook is deprecated since `feathers-authentication@1.x`. Should'n this line be removed from docs ?

**Comment by eddyystop** [comment]
Isn't there a replacement hook for it?

**Comment by daffl** [comment]
The main authentication hook (`auth.authenticate(strategies)`) is handling that now.

**Comment by sylvainlap** [comment]
PR: https://github.com/feathersjs/feathers-authentication-management/pull/56

**Comment by eddyystop** [comment]
Thanks!
