### ISSUE TITLE
Prevent changes on PATCH

### ISSUE THREAD

**Issue by sylvainlap** [feathersjs/feathers-authentication-management#54]
Currently, it is really easy to PATCH a user to set isVerified, or a resetToken.
Maybe you should add a built-in hook to prevent these changes on PATCH /user/:id ?

**Comment by eddyystop** [comment]
Whatever additional controls are implemented, someone will come up with a valid, opposing use case.

You can use the preventChange hook https://docs.feathersjs.com/api/hooks-common.html#preventchanges

Feel free to make a PR to the docs with a small note mentioning the situation.

**Comment by sylvainlap** [comment]
PR: https://github.com/feathersjs/feathers-authentication-management/pull/56

**Comment by eddyystop** [comment]
Merged. It'll be pushed as 0.4.3.
