### ISSUE TITLE
removeVerification not suitable as an after find hook

### ISSUE THREAD

**Issue by sylvainlap** [feathersjs/feathers-authentication-management#55]
In this line: https://github.com/feathersjs/feathers-authentication-management/blob/master/src/hooks.js#L40, removeVerification hook consider that result is a user.

However, in a find hook, result could be a paginated data.

**Comment by eddyystop** [comment]
You're right. Thanks.

**Comment by eddyystop** [comment]
I'll handle this when I have time.

**Comment by sylvainlap** [comment]
I don't think that feathers-auth-management docs are available on docs.feathersjs.com

**Comment by eddyystop** [comment]
They've been restored now.
