### ISSUE TITLE
update package on npm

### ISSUE THREAD

**Issue by letranloc** [feathersjs/feathers-authentication-management#6]

**Comment by eddyystop** [comment]
Published the latest as 0.1.0

**Comment by letranloc** [comment]
I think It's better when you include your `lib` folder into repo. So, we can use something like
```json
"feathers-authentication-management": "https://github.com/feathersjs/feathers-authentication-management"
```
for testing latest code instead dependent on the package `feathers-authentication-management` on npm

**Comment by eddyystop** [comment]
We prefer you download from npm. That gives us extra flexibility for what's in the repo. Not including lib/ in GitHub is a standard for all the repos.

You can run `npm test` on the repo and everything will be created for you.

**Comment by letranloc** [comment]
Ok. thanks you! 🙂
