### ISSUE TITLE
oops, where can I find the docs?

### ISSUE THREAD

**Issue by beeplin** [feathersjs/feathers-authentication-management#7]
Kept busy on other stuffs for the last couple of weeks~ How is it going?

I found the docs are missing. the readme.md refers to feathers Auk doc but I cannot find it in the Auk doc.

**Comment by eddyystop** [comment]
Its at Authentication / Password management / Local or https://docs.feathersjs.com/v/auk/authentication/management.html .

I look forward to your feedback.

Things are going fine. Thanks for asking. You may be interested in:
- populate, serialize, dePopulate are merged in feathers-hooks-common https://docs.feathersjs.com/v/auk/hooks/common/populate.html
- We now have iffElse, iff..else, when, unless, some, every hooks https://docs.feathersjs.com/v/auk/hooks/common/conditional.html
- validateSchema is in review https://github.com/feathersjs/feathers-hooks-common/pull/68
- $client is in review https://github.com/feathersjs/feathers-hooks-common/pull/65
- We are working on extending some hooks to work with event filters and authentication permissions. Review at https://github.com/feathersjs/feathers-hooks-common/pull/75
- Best Buy used Feathersjs for its teaching REST API tool https://github.com/BestBuy/api-playground . To complete the Feathers picture we wrote a front-end https://github.com/feathersjs/api-playground-client

Any comments you have would be welcome.

Authentication v1 and permissions is coming along. Docs are still being completed in the Auk branch. You might save yourself some time by waiting a week before starting to use it. Read the migration guide.

**Comment by beeplin** [comment]
Coooool~ You guys are awesome!

I have dig into the source code of authv1 and permissions and now figured out how to use them. Of course I can wait a week to see the final doc. :)

Will check the docs you mentioned soon.

**Comment by eddyystop** [comment]
Nice. I will ask you questions when I have issues with auth v1. :)

**Comment by beeplin** [comment]
I have also noticed the news that BestBuy are using feathers. BestBuy knows what is good. Haha .
