### ISSUE TITLE
congratulations for v1.0!!!

### ISSUE THREAD

**Issue by beeplin** [feathersjs/feathers-authentication-management#72]
I didn't see any breaking changes in the change log~ cool~

**Comment by eddyystop** [comment]
Hi. Its nice to hear from you again.

The v1.0 encodes the tokens stored in the user DB. Tokens issued by the previous version will no longer be valid. That's a breaking change of sorts.

Most of the PRs for v1.0 were produced by the community and its so nice to see that.

**Comment by beeplin** [comment]
Get it! Nice community job!~
